/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    fontFamily: {
      sans: ['"Noto Sans"', "sans-serif"],
    },
    colors: {
      primary: "#FFE833",
      secondary: "#19191A",
      accent: "#B26EF7",
      background: "#050505",
      body: "#FAFAFA",
      "spotify-green": "#1DB954",
      "accent-1": "#FF9785",
      "accent-2": "#33FF82",
      "accent-3": "#A3AEFF",
      "accent-4": "#33FFE8",
      "accent-5": "#F28FFF",
    },
    fontColors: {
      subtitle: "#CACACA",
    },
    fontSize: {
      sm: "1rem",
      base: "1.5rem",
      lg: "2rem",
      xl: "2.25rem",
      "2xl": "5.3125rem",
    },
    extend: {
      spacing: {
        "3xs": "0.5rem",
        "2xs": "1rem",
        xs: "1.5rem",
        sm: "2rem",
        md: "2.5rem",
        lg: "3rem",
        xl: "3.5rem",
        "2xl": "4rem",
        "3xl": "5rem",
        "4xl": "8rem",
      },
      fontSize: {
        h1: "5.3125rem",
        h2: "3.25rem",
        h3: "2rem",
        subtitle: "1.5rem",
        body: "1.25rem",
        small: "1rem",
        pretitle: "0.875rem",
        button: "2rem",
        link: "1.5rem",
      },
      lineHeight: {
        h1: "5.5rem",
        h2: "4rem",
        h3: "3.5rem",
        subtitle: "2.25rem",
        body: "2rem",
        small: "1.5rem",
        pretitle: "1.5rem",
        button: "3rem",
        link: "2.25rem",
      },
    },
  },
  plugins: [],
};
